### ISSUE TITLE
GetLinks Regex Gets A and LINK elements.

### ISSUE THREAD

**Issue by nicksloan** [pghpy/python-intro#3]
The GetLinks function needs to be reconsidered. As it stands, it gets A and LINK elements. LINK elements are used to include assets for the page, such as CSS files, fav icons and RSS feeds. They will be returning URLs that do not return HTML data, and as such, aren't useful in a search engine.

```
r'<a\s+[^>]*href\s*=\s*"([^"]+)"[^>]*>'
```

I've added a match for the A element. I've removed the allowance of whitespace inside the quotes of the HREF attribute. It may be valid HTML, but frankly, you'd have to be insane to write HTML that way. More likely, that's going to be a signal of something javascripty that is not a URL.

This worked great on google.com and yahoo.com.

**Comment by chadwhitacre** [comment]
💃
